name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.SEMANTIC_RELEASE }}
          allow-initial-development-versions: true
          changelog-file: CHANGELOG.md