name: Run tests
on:
  workflow_dispatch:
  pull_request:
    branch: main
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read # for checkout

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4.0.0
      - name: Install dependencies
        run: go mod download
      - name: Run local-setup
        run: |
          git clone https://github.com/matter-labs/local-setup.git
          pushd local-setup
          docker-compose up -d
          popd
      - name: Wait for local-setup to be ready
        run: go run ./scripts/wait.go
      - name: Run tests
        run: go test ./test/...