name: Run tests
on:
  push:
    branches: [ main, beta ]
  workflow_dispatch:
  pull_request:
    branches: [main, beta ]
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read # for checkout

jobs:
  eth-based-chain-test:
    name: ETH-based Chain Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5.0.0
      - name: Install dependencies
        run: go mod download
      - name: Run local-setup
        run: |
          git clone https://github.com/matter-labs/local-setup.git
          pushd local-setup
          ./start-zk-chains.sh
          popd
      - name: Run tests
        run: make run-tests-on-eth-based-chain

  non-eth-based-chain-test:
    name: Non-ETH-based Chain Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5.0.0
      - name: Install dependencies
        run: go mod download
      - name: Run local-setup
        run: |
          git clone https://github.com/matter-labs/local-setup.git
          pushd local-setup
          ./start-zk-chains.sh
          popd
      - name: Run tests
        run: make run-tests-on-non-eth-based-chain
